client_config_backend: file
client_config_file: sandbox/server/backends/resources/utils/osworld-settings/googledrive/client_secrets.json

save_credentials: True
save_credentials_backend: file
save_credentials_file: sandbox/server/backends/resources/utils/osworld-settings/googledrive/credentials.json

get_refresh_token: True
